# Sponsorship options for n8n Pulse
# Uncomment and fill in the platforms you want to use

github: gxjansen
# ko_fi: # your ko-fi username
# buy_me_a_coffee: # your buymeacoffee username
# open_collective: # your open collective username
# custom: ['https://your-donation-link.com']
